function out = SlowpassBW(in,stop,order)

out=in;
s=size(in.data);
%LOWPASSBW8 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.9 and the Signal Processing Toolbox 6.12.
%
% Generated on: 22-Mar-2013 19:00:43
%

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = in.sampleFreq;  % Sampling Frequency

if nargin>2   % Set filter Order
    N   = order;
else
    N=8; 
end

Fc = stop;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
[b,a] = sos2tf(Hd.sosMatrix,Hd.ScaleValues);

out.data=reshape(filtfilt(b,a,in.data(:)),s(1),s(2));



% [EOF]
