function out = SlowpassBW8(in,stop)

out=in;
s=size(in.data);
%LOWPASSBW8 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.9 and the Signal Processing Toolbox 6.12.
%
% Generated on: 22-Mar-2013 19:00:43
%

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = in.sampleFreq;  % Sampling Frequency

N  = 8;   % Order
Fc = stop;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
out.data=filter(Hd,in.data);
out.data=reshape(hp.filtfilthd(Hd,in.data(:)),s(1),s(2));

% [EOF]
